name: anything-llm

services:
  anything-llm:
    container_name: anything-llm
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        ARG_UID: ${UID:-1000}
        ARG_GID: ${GID:-1000}
    cap_add:
      - SYS_ADMIN
    volumes:
      - "/mnt/stor/ssd-lv/volumes/anyllm/env:/app/server/.env"
      - "/mnt/stor/ssd-lv/volumes/anyllm/storage:/app/server/storage"
      - "/mnt/stor/ssd-lv/volumes/anyllm/collector/hotdir/:/app/collector/hotdir"
      - "/mnt/stor/ssd-lv/volumes/anyllm/collector/outputs/:/app/collector/outputs"
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3001:3001"
    #env_file:
    #  - ./docker/stack.env
      #extra hosts it a trick to perform abiliuty of communication btw cont and host
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    networks:
      net51:
        ipv4_address: 10.0.51.164

networks:
  net51:
    name: 'net51'
    external: 'true'
